name: M∑овет
description: >
    M∑
about: >
    Непопулярный подкаст о науке и всякой херне вокруг
url: "https://msovet.com"
markdown: kramdown
highlighter: rouge
future: true

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

disqus_shortname: